#!/bin/bash

# This is a dummy script.
# It can be safely run for testing purposes.
# It also provides a template for own scripts.

# Call 'error' to signal unsuccesful task and
# 'exit_error' to also quit immediately.


do_config()
{
    echo "Configuring..."
}


do_build()
{
    echo "Building..."
}

do_package()
{
    echo "Packaging..."
}

do_test()
{
    NA
}

do_clean()
{
    NA
}

do_purge()
{
    NA
}
